### ISSUE TITLE
SvelteKit DB ?

### ISSUE THREAD

**Issue by daslicht** [ShindouMihou/Flora#4]
Hi,
I apologize to contact you here but I havent found another way yet.

After reading this article from you, I wonder which Database ORM etc you now use with sveltekit ?

https://blog.mihou.pw/posts/from-laravel-to-sveltekit

**Comment by ShindouMihou** [comment]
Hello @daslicht, sorry for the late response, you can connect SvelteKit with any database you'd like. I tend to use MongoDB because it has great official drivers that do not need any ORMs at all, you can also use it with Mongoose or related. Additionally, if you are using SQL, then a good database ORM that I would recommend is Prisma.

Although, in most scenarios, unless needed, I tend to use SvelteKit for frontend pairing it with the likes of Svelte-Query or even native fetch to connect with a backend that is written in Golang or Kotlin. You are more than free to use whichever ORM though. =w=

**Comment by daslicht** [comment]
Thanks for the reply! An Javascript ORM like [ReadBeanPHP](https://www.redbeanphp.com/index.php?p=/crud) woudl be awesome

**Comment by daslicht** [comment]
Thanks for the reply! An Javascript ORM like [ReadBeanPHP](https://www.redbeanphp.com/index.php?p=/crud) would be awesome.
